### ISSUE TITLE
Trained model can not be downloaded now

### ISSUE THREAD

**Issue by leyuan-sun** [sagieppel/Focusing-attention-of-Fully-convolutional-neural-networks-on-Region-of-interest-ROI-input-map-#1]
please update the link of these, thanks ahead!!!

**Comment by leyuan-sun** [comment]
Also the checkpoint file is needed, thanks a lot !!

**Comment by sagieppel** [comment]
This is really ancient work, will not recommend using it in 2021 :-)
Newer and much stronger model available here:
https://github.com/sagieppel/Segmenting-givne-region-of-an-image-using-neural-net-with-ROI-attention-input

**Comment by RakugenSon** [comment]
> This is really ancient work, will not recommend using it in 2020 :-)
> Newer and much stronger model available here:
> https://github.com/sagieppel/Detecting-and-segmenting-and-classifying-materials-inside-vessels-in-images-using-convolutional-net

Thank u for your reply,  I am not using it to do segmentation, your ROI idea is my point, I would like to extract features using ROI from different layers, could u give me your trained model and corresponging checkpoint, thanks!

**Comment by leyuan-sun** [comment]
> This is really ancient work, will not recommend using it in 2020 :-)
> Newer and much stronger model available here:
> https://github.com/sagieppel/Segmenting-givne-region-of-an-image-using-neural-net-with-ROI-attention-input
Thank u for your reply, I am not using it to do segmentation, your ROI idea is my point, I would like to extract features using ROI from different layers, could u give me your trained model and corresponging checkpoint, thanks!

**Comment by sagieppel** [comment]
I didn't keep the trained models and the host deleted so they are probably lost now
Can give u a much better model implemented in PyTorch which also uses the ROI approach.
If u also want the trained model can give you this in a week or two (Accidently I am working on it at the moment).

**Comment by leyuan-sun** [comment]
> I didn't keep the trained models and the host deleted so they are probably lost now
> Can give u a much better model implemented in PyTorch which also uses the ROI approach.
> If u also want the trained model can give you this in a week or two (Accidently I am working on it at the moment).

Thanks, I want both of them. I am training the old one now, if it works, I will tell you. About the new one with ROI, please if you are convenient.

**Comment by leyuan-sun** [comment]
> > I didn't keep the trained models and the host deleted so they are probably lost now
> > Can give u a much better model implemented in PyTorch which also uses the ROI approach.
> > If u also want the trained model can give you this in a week or two (Accidently I am working on it at the moment).
> 
> Thanks, I want both of them. I am training the old one now, if it works, I will tell you. About the new one with ROI, please if you are convenient.

The one I trained works.

**Comment by sagieppel** [comment]
Great:)

**Comment by leyuan-sun** [comment]
> Great:)

Could u give me some guides about how to plot the feature map, relevance map and normalized map in your paper?

**Comment by sagieppel** [comment]
The layers  you are looking for are:
"RelevanceMap" =  the relevance maps for all the batch  
"conv1_2 "= the normalize feature maps   
"conv1_1" = the features map (before normalization
(See file BuildNetVgg16.py lines 52-54)

**Comment by rginjapan** [comment]
> The layers you are looking for are:
> "RelevanceMap" = the relevance maps for all the batch
> "conv1_2 "= the normalize feature maps
> "conv1_1" = the features map (before normalization
> (See file BuildNetVgg16.py lines 52-54)

Thanks, I found it, the shape is shape=(?, ?, ?, 64) for the first and third map, I know there are 64 maps

**Comment by leyuan-sun** [comment]
> The layers you are looking for are:
> "RelevanceMap" = the relevance maps for all the batch
> "conv1_2 "= the normalize feature maps
> "conv1_1" = the features map (before normalization
> (See file BuildNetVgg16.py lines 52-54)

Thanks, I used sess.run(Net.RelevanceMap, , ,) in Inference.py to extract it successfully

**Comment by leyuan-sun** [comment]
Hello, not about the code. If I would like to remove the features including the information from ROI boundary which extracting from CNN. Do you have some suggestions? I think your method still keeps the information from ROI boundary.

**Comment by sagieppel** [comment]
Not sure what you mean, but information from boundaries can be quiet important  remove it is not a good idea.
You can set the features at the boundary to zero but not sure why.
